Repository andela/technites-bn-backend, pull requests merged in 2019-11, with the labels that each got.

#75 #169672993 Fix Get requests Route
  .travis.yml
  package-lock.json
  package.json
  src/controllers/RequestController.js
  src/routes/RequestRoutes.js
Labels: ready for review

#72 #168050033 users should be able to chat on barefoot nomad
  client/index.html
  client/worker.js
  src/controllers/AccomodationController.js
  src/controllers/ChatController.js
  src/controllers/UserController.js
  src/database/config/config.js
  src/database/migrations/20191013131024-create-chats.js
  src/database/models/chats.js
  src/database/models/user.js
  src/database/seeders/20190910075430-test-user.js
  src/database/seeders/20190918093500-request.js
  src/index.js
  src/routes/AuthRoutes.js
  src/routes/UserRoutes.js
  src/services/ChatServices.js
  src/services/NotificationServices.js
  src/utils/EventListeners.js
  src/utils/Response.js
  src/validation/Validations.js
  test/Accommodations.spec.js
  test/Chat.spec.js
  test/UsersRequest.spec.js
  test/index.spec.js
Labels: Ready for merge

#81 Should mark one specific notification as read
  src/controllers/RequestController.js
  src/controllers/UserController.js
  src/routes/RequestRoutes.js
  src/routes/UserRoutes.js
  test/Accommodations.spec.js
Labels: ready for review

#63 #168834864 Improve maintainability of the codebase
  client/worker.js
  src/controllers/AccomodationController.js
  src/controllers/RequestController.js
  src/controllers/UserController.js
  src/database/models/index.js
  src/database/seeders/20190910075430-test-user.js
  src/routes/AccomodationsRoutes.js
  src/routes/RequestRoutes.js
  src/routes/UserRoutes.js
  src/services/NotificationServices.js
  src/services/RequestServices.js
  src/services/UserServices.js
  src/utils/GetRoleUtil.js
  src/utils/ImageUploader.js
  src/utils/SearchUtils.js
  src/utils/UserServicesResponse.js
  src/validation/Validations.js
  test/Accommodations.spec.js
  test/UsersRequest.spec.js
Labels: work in progress

#69 #168050020 Managers should receive notifications for edited requests
  client/index.html
  client/worker.js
  src/controllers/AccomodationController.js
  src/controllers/UserController.js
  src/database/models/index.js
  src/database/models/request.js
  src/services/AccomodationServices.js
  src/services/NotificationServices.js
  src/utils/EventListeners.js
  src/validation/UserValidation.js
Labels: Ready for merge

#68 #168050014 Profile Information from Travel Request Page
  src/controllers/RequestController.js
  src/database/migrations/20190904073354-create-user.js
  src/database/migrations/20190917120002-create-request.js
  src/database/models/request.js
  src/database/models/user.js
  src/database/seeders/20190910075430-test-user.js
  src/database/seeders/20190918093500-request.js
  src/middlewares/RequestValidation.js
  src/middlewares/checkCookies.js
  src/routes/RequestRoutes.js
  src/services/UserServices.js
  src/utils/BookingCronJobs.js
  src/validation/Validations.js
  test/Accommodations.spec.js
  test/Admin.spec.js
  test/Comment.spec.js
  test/CronJob.spec.js
  test/UsersRequest.spec.js
Labels: ready for review
