Repository andela/technites-bn-backend, pull requests merged in 2019-09, with the labels that each got.

#2 #168238483 Add a pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Awaiting TTL's approval

#1 #168049986 Configuring ESLint
  .eslintrc.js
  package-lock.json
  package.json
  src/index.js
Labels: Awaiting TTL's approval

#7 #168257828 Setup babel (ES6)
  .babelrc
  package-lock.json
  package.json
Labels: Awaiting TTL's approval

#8 #168049990 Setup dotenv
  .env.example
  src/index.js
Labels: Awaiting TTL's approval

#6 #168049984 Configure BareFoot Nomad to use PostgreSQL as DB Engine
  package-lock.json
  package.json
  src/config/passport.js
  src/index.js
  src/models/User.js
  src/routes/api/users.js
Labels: Awaiting TTL's approval

#3 #168049988 Integrate TravisCI with readme badge
  .travis.yml
  README.md
Labels: Awaiting TTL's approval

#5 #168049987 Integrate HoundCI with badge attached to readme
  .eslintrc
  .eslintrc.js
  .hound.yml
  README.md
  package-lock.json
Labels: Awaiting TTL's approval

#9 #168049993 Setup API documentation using swagger
  package-lock.json
  package.json
  src/routes/index.js
  swagger.json
Labels: Awaiting TTL's approval

#13 #168049985 Setup Sequelize
  .env.example
  .sequelizerc
  README.md
  package-lock.json
  package.json
  src/database/config.js
  src/database/config/config.js
  src/database/migrations/20190904073354-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/models/User.js
Labels: ready for review

#10 #168049989 Setup unit testing
  package-lock.json
  package.json
  test/index.js
Labels: Awaiting TTL's approval, ready for review

#17 #168311192 Fix test coverage status
  .travis.yml
  package.json
Labels: Awaiting TTL's approval

#18 #168315936 Add the docker compose file
  .gitignore
  docker-compose.yml
Labels: Awaiting TTL's approval

#19 #168049995 Deploy base application to Heroku
  .gitignore
  Procfile
  package.json
Labels: ready for review

#20 #168311192 Fix test coverage status
  README.md
Labels: ready for review

#21 #168340940 Add configuration for enabling review apps to run on heroku
  app.json
Labels: ready for review

#27 #168049996 On successful registration, users should receive a JWT
  .env.example
  .travis.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/controllers/OAuthController.js
  src/controllers/UserController.js
  src/database/migrations/20190904073354-create-user.js
  src/database/models/user.js
  src/index.js
  src/routes/UserRoutes.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
  src/services/UserServices.js
  src/utils/AuthHelper.js
  src/utils/UserUtils.js
  swagger.json
  test/User.spec.js
Labels: Awaiting TTL's approval

#31 #168050002 Logout Functionality
  .env.example
  .travis.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/controllers/UserController.js
  src/database/migrations/20190904073354-create-user.js
  src/middlewares/UserAuthentication.js
  src/middlewares/index.js
  src/routes/UserRoutes.js
  src/routes/index.js
  src/utils/AuthHelper.js
  src/utils/ConfirmationEmail.js
  src/utils/Mail.js
  src/utils/RedisConnection.js
  src/utils/Response.js
  src/validation/UserValidation.js
  test/User.spec.js
  test/index.js
Labels: ready for review

#32 #168504400 Destroy token after resetting password
  .env.example
  src/controllers/UserController.js
  src/database/migrations/20190909094109-create-password-resets.js
  src/database/models/PasswordResets.js
  src/database/seeders/20190910075430-test-user.js
  src/services/UserServices.js
  src/utils/Mail.js
  src/utils/OAuthCallback.js
  test/OAuth.spec.js
  test/User.spec.js
Labels: Awaiting TTL's approval

#33 #168050005 Blacklist tokens appropriately
  docker-compose.yml
  src/controllers/UserController.js
  src/middlewares/UserAuthentication.js
  test/User.spec.js
Labels: Awaiting TTL's approval

#36 #168050003 Profile page settings
  .env.example
  docker-compose.yml
  package-lock.json
  package.json
  src/controllers/UserController.js
  src/database/migrations/20190904073354-create-user.js
  src/database/models/user.js
  src/database/seeders/20190910075430-test-user.js
  src/middlewares/UserAuthentication.js
  src/routes/AuthRoutes.js
  src/routes/UserRoutes.js
  src/routes/index.js
  src/services/UserServices.js
  src/utils/UserServicesResponse.js
  src/utils/assets/Profile.png
  src/utils/assets/Test.rtf
  src/validation/Validations.js
  swagger.json
  test/User.spec.js
Labels: Awaiting TTL's approval

#34 #168050010 User Role Settings
  .env.example
  .gitignore
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  src/controllers/AdminController.js
  src/controllers/UserController.js
  src/database/migrations/20190904073354-create-user.js
  src/database/migrations/20190917071255-create-role.js
  src/database/models/role.js
  src/database/seeders/20190910075430-test-user.js
  src/database/seeders/20190917101843-role-values.js
  src/middlewares/UserAuthentication.js
  src/routes/AdminRoutes.js
  src/routes/AuthRoutes.js
  src/routes/UserRoutes.js
  src/routes/index.js
  src/services/UserServices.js
  src/utils/AuthHelper.js
  src/utils/GetRoleUtil.js
  src/validation/UserValidation.js
  swagger.json
  test/Admin.spec.js
  test/User.spec.js
  test/UtilsUnitTest.spec.js
Labels: Awaiting TTL's approval

#35 #168050009 Integrate the requests table to the backend
  package.json
  src/controllers/RequestController.js
  src/database/migrations/20190917120002-create-request.js
  src/database/migrations/20190917142728-create-location.js
  src/database/models/location.js
  src/database/models/request.js
  src/database/seeders/20190918093500-request.js
  src/middlewares/UserAuthentication.js
  src/routes/AuthRoutes.js
  src/routes/UserRoutes.js
  src/services/RequestServices.js
  swagger.json
  test/OAuth.spec.js
  test/Request.spec.js
  test/__mocks__/MockData.json
Labels: Awaiting TTL's approval

#40 #168050005 Users should be able to make one-way trip request
  src/controllers/RequestController.js
  src/database/seeders/20190910075430-test-user.js
  src/middlewares/RequestValidation.js
  src/routes/AuthRoutes.js
  src/routes/UserRoutes.js
  src/services/RequestServices.js
  src/utils/ConfirmationRequest.js
  src/validation/Validations.js
  test/Request.spec.js
Labels: ready for review

#39 #168050006 Users should be able to make Return trip
  src/validation/Validations.js
  test/Request.spec.js
Labels: ready for review

#41 #168050024 Users should be able to edit requests with status Pending
  src/controllers/RequestController.js
  src/controllers/UserController.js
  src/database/seeders/20190910075430-test-user.js
  src/database/seeders/20190918093500-request.js
  src/database/seeders/20190923124433-add-locations.js
  src/routes/RequestRoutes.js
  src/routes/UserRoutes.js
  src/routes/index.js
  src/services/RequestServices.js
  src/utils/ConfirmationRequest.js
  src/utils/UpdateRequest.js
  src/utils/UserRequest.js
  src/validation/Validations.js
  swagger.json
  test/UsersRequest.spec.js
Labels: Awaiting TTL's approval

#43 #168050007 Users should be able to make multi city request
  src/controllers/RequestController.js
  src/database/seeders/20190910075430-test-user.js
  src/database/seeders/20190918093500-request.js
  src/middlewares/RequestValidation.js
  src/routes/RequestRoutes.js
  src/routes/UserRoutes.js
  src/services/RequestServices.js
  src/utils/ConfirmationRequest.js
  src/utils/UserRequest.js
  src/validation/Validations.js
  test/UsersRequest.spec.js
Labels: Awaiting TTL's approval

#48 #168050013 Users should be able to comment on Travel requests
  package-lock.json
  package.json
  src/controllers/CommentController.js
  src/database/migrations/20190923194341-create-comment.js
  src/database/models/comment.js
  src/database/models/request.js
  src/database/models/user.js
  src/database/seeders/20190910075430-test-user.js
  src/database/seeders/20190918093500-request.js
  src/index.js
  src/routes/UserRoutes.js
  src/routes/index.js
  src/services/RequestServices.js
  src/services/UserServices.js
  src/utils/UserUtils.js
  src/validation/UserValidation.js
  swagger.json
  test/Comment.spec.js
  test/User.spec.js
  test/UsersRequest.spec.js
Labels: Awaiting TTL's approval

#44 #168050017 Add Search Functionality
  src/controllers/RequestController.js
  src/routes/RequestRoutes.js
  src/routes/index.js
  src/services/RequestServices.js
  src/validation/QueryValidation.js
  swagger.json
  test/UsersRequest.spec.js
Labels: Awaiting TTL's approval

#50 #168050016 Delete comment
  src/controllers/CommentController.js
  src/database/migrations/20190923194341-create-comment.js
  src/database/models/comment.js
  src/database/seeders/20190918093500-request.js
  src/routes/UserRoutes.js
  src/services/RequestServices.js
  swagger.json
  test/Comment.spec.js
  test/User.spec.js
Labels: ready for review

#45 #168050011 Reject Request (By Requester’s Manager)
  src/controllers/RequestController.js
  src/database/models/request.js
  src/database/models/user.js
  src/database/seeders/20190910075430-test-user.js
  src/index.js
  src/middlewares/AttachUser.js
  src/routes/RequestRoutes.js
  src/routes/UserRoutes.js
  src/services/RequestServices.js
  src/services/UserServices.js
  src/utils/ConfirmationRequest.js
  src/utils/MailHelper.js
  src/utils/UpdateRequest.js
  src/utils/UserRequest.js
  src/validation/UserValidation.js
  src/validation/Validations.js
  test/UsersRequest.spec.js
Labels: Awaiting TTL's approval

#49 #168050012 Avail request for Approval
  package-lock.json
  package.json
  src/controllers/RequestController.js
  src/index.js
  src/middlewares/AttachUser.js
  src/routes/RequestRoutes.js
  src/services/RequestServices.js
  src/services/UserServices.js
  swagger.json
  test/Accommodation.spec.js
  test/Common.spec.js
  test/Manager.spec.js
  test/UsersRequest.spec.js
  test/index.spec.js
Labels: ready for review

#46 #168050032 Most travelled destination
  src/controllers/RequestController.js
  src/database/seeders/20190910075430-test-user.js
  src/database/seeders/20190918093500-request.js
  src/database/seeders/20190923124433-add-locations.js
  src/routes/RequestRoutes.js
  src/services/RequestServices.js
  src/validation/Validations.js
  test/Comment.spec.js
  test/UsersRequest.spec.js
Labels: Awaiting TTL's approval

#51 #168748854 Errors should be handled well and logged in a log file
  .env.example
  package-lock.json
  package.json
  src/controllers/AccomodationController.js
  src/index.js
  src/utils/ErrorLogger.js
Labels: Awaiting TTL's approval
